defaults: &defaults
  app_name: 'tesla'
development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
  AWS_ACCESS_KEY_ID: 'AKIAIL7WBPVNEWAMCP5A'
  AWS_SECRET_ACCESS_KEY: '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'
  AWS_S3_BUCKET: 'teslaweb'
  AWS_REGION: 'ap-northeast-1'
